# Metadata
site_name: PPS - Federico Rodriguez Ferro
site_description: Seguridad de entornos contenerizados con enfoque en Kubernetes.
site_author: Rodriguez Ferro Federico

# Github
repo_url: https://github.com/danunziata/pps_fede_Ferro_2024
repo_name: danunziata/pps_fede_Ferro_2024

nav:
  - Introducción: index.md
  - Conceptos: contexto.md
  - Kubernetes:
    - Instalación: kubernetes/instalacion.md
    - Balanceador de Cargas: kubernetes/loadbalancer.md
    - Acceso a Servicios: kubernetes/ingress.md
    - Administración: kubernetes/lens.md
    - Service Mesh: kubernetes/servicemesh.md
  - Seguridad:
    - Autentificación: seguridad/autentificacion.md
    - Seguridad: seguridad/seguridad.md
    - Monitoreo: seguridad/monitoreo.md
    - Escaneo: seguridad/scanning.md
    - Certificación: seguridad/certificacion.md
    - Copias de Seguridad: seguridad/backup.md
  - Proyecto:
    - Metodologia de Trabajo: proyecto/metodologia.md
    - Contribución: proyecto/contributing.md

# Design
theme:
  name: material
  
  icon:
    repo: fontawesome/brands/github
  
  language: es

  features:
    - navigation.sections
    - navigation.path
    - navigation.top
  

  palette: 

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: blue grey
      accent: lime
      
        
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: blue grey
      accent: purple
        
        

# Links footer
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/danunziata/pps_fede_Ferro_2024
      name: Repo URL


  # More metadata
  meta:
  author: Rodriguez Ferro Federico
  description: Seguridad de entornos contenerizados con enfoque en Kubernetes.
  keywords: Ingeniería, Kubernetes, Engineering, Ingeniería, Telecomunicaciones, Security, Seguridad, Monitoring, Observability

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Copyright footer
copyright: |
  &copy; 2024 <a href="https://www.ing.unrc.edu.ar/inicio.php"  target="_blank" rel="noopener">Universidad Nacional de Río cuarto | Facultad de Ingeniería</a>