apiVersion: v1
kind: Service
metadata:
  name: authentik-service
spec:
  selector:
    app: authentik
  ports:
  - name: http
    protocol: TCP
    port: 80 # change as required
    targetPort: 9000
  - name: https
    protocol: TCP
    port: 443 # change as required
    targetPort: 9443
  type: LoadBalancer
