---

apiVersion: v1
kind: Service
metadata:
  name: emqx
  labels:
    service: emqx
spec:
  ports:
    - name: dashboard
      port: 18083
      protocol: TCP
      targetPort: 18083
      nodePort: 31002
    - name: mqtt
      port: 1883
      protocol: TCP
      targetPort: 1883
      nodePort: 31003
  selector:
    service: emqx
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    service: influxdb
spec:
  ports:
    - name: dashboard
      port: 8086
      targetPort: 8086
      nodePort: 31001
  selector:
    service: influxdb
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 31000
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer