apiVersion: v1
kind: Service
metadata:
  name: influxdb
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: influxdb
spec:
  ports:
    - name: "8086"
      port: 8086
      targetPort: 8086
      nodePort: 31001
  selector:
    io.kompose.service: influxdb
  type: LoadBalancer
