  data:
    grafana.ini: |
      [analytics]
      check_for_updates = true
      [grafana_net]
      url = https://grafana.net
      [log]
      mode = console
      [paths]
      data = /var/lib/grafana/
      logs = /var/log/grafana
      plugins = /var/lib/grafana/plugins
      provisioning = /etc/grafana/provisioning
      [server]
      domain = localhost
      [auth]
      signout_redirect_url = https://authentik.company/application/o/<Slug of the application from above>/end-session/
      oauth_auto_login = true
      [auth.generic_oauth]
      name = authentik
      enabled = true
      client_id = <Client ID from above>
      client_secret = <Client Secret from above>
      scopes = openid email profile
      auth_url = https://authentik.company/application/o/authorize/
      token_url = https://authentik.company/application/o/token/
      api_url = https://authentik.company/application/o/userinfo/
      role_attribute_path = contains(groups, 'authentik Admins') && 'Admin' || contains(groups, 'Grafana Editors') && 'Editor' || 'Viewer'
      tls_skip_verify_insecure = true
      [security]
      cookie_samesite = none
      cookie_secure = false