apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegrafinput
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: telegrafinput
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: telegrafinput
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      labels:
        io.kompose.service: telegrafinput
    spec:
      containers:
        - name: telegrafinput
          image: telegraf:1.22.4
          volumeMounts:
            - mountPath: /etc/telegraf
              name: config-volume
            - mountPath: /tmp
              name: telegrafinput-claim1
      restartPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: telegraf-config-input
        - name: telegrafinput-claim1
          persistentVolumeClaim:
            claimName: telegrafinput-claim1