apiVersion: v1
kind: Pod
metadata:
  name: telegrafoutput
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: telegrafoutput
spec:
  containers:
    - image: telegraf:1.22.4
      name: telegrafoutput
      volumeMounts:
        - mountPath: /etc/telegraf
          name: config-volume2
  restartPolicy: OnFailure
  volumes:
    - name: config-volume2
      configMap:
        name: telegraf-config-output
