apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: telegrafoutput-claim0
  labels:
    io.kompose.service: telegrafoutput-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard