apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emqx-claim1
  labels:
    io.kompose.service: emqx-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard